-- Question#011 - Query 9
USE AMG;

SELECT C.NAME, COUNT(*) AS 'PLANES OWNED'
FROM CORPORATION C
JOIN OWNS O ON C.OWNERID = O.OWNER_ID
JOIN AIRPLANE A ON O.REG_NO = A.REG_NO
GROUP BY C.OWNERID, C.NAME
ORDER BY COUNT(*) DESC;