-- Question#13 - Query 11
USE AMG;

SELECT CR.NAME AS 'CORPORATION NAME', PR.NAME AS 'PERSON NAME'
FROM OWNER AS OW
LEFT JOIN CORPORATION CR ON CR.OWNERID = OW.OWNERID
LEFT JOIN PERSON PR ON PR.SSN = OW.OWNERID
JOIN OWNS O ON O.OWNER_ID = OW.OWNERID
JOIN AIRPLANE A ON A.REG_NO = O.REG_NO
WHERE NEED_MNT IS NOT NULL AND A.REG_NO IN (
	SELECT A.REG_NO
	FROM AIRPLANE A
	JOIN EMP_QUALIFICATION EQ ON A.NEED_MNT = EQ.QUAL
	WHERE EQ.SSN NOT IN (
		SELECT WO.SSN
		FROM AIRPLANE A
		JOIN WORKS_ON WO ON WO.MODEL = A.MODEL
		WHERE A.NEED_MNT IS NOT NULL
	)
);