-- Question#14 - Query 12
USE AMG;

SELECT P.NAME AS 'PERSON NAME', P.PHONE AS 'PERSON PHONE', C.NAME AS 'COPERATION NAME', C.PHONE AS 'COPERATION PHONE'
FROM AIRPLANE A
JOIN HANGAR HG ON HG.NUMBER = A.HG_NO
JOIN OWNS O ON A.REG_NO = O.REG_NO
LEFT JOIN PERSON P ON P.SSN = O.OWNER_ID
LEFT JOIN CORPORATION C ON C.OWNERID = O.OWNER_ID
WHERE (C.ADDRESS  LIKE '%'+HG.LOCATION+'%') OR (P.ADDRESS  LIKE '%'+HG.LOCATION+'%');