-- Question#16 - Query 14
USE AMG;

SELECT P.NAME, P.PHONE, SUM(S.HOURS) AS 'HOURS WORKED'
FROM OWNS OW
JOIN AIRPLANE A ON A.REG_NO = OW.REG_NO
JOIN PLANE_SERVICE PS ON PS.PREG_NO = A.REG_NO
JOIN SERVICE S ON S.S_DATE = PS.SER_DATE AND S.WORK_CODE = PS.SER_CODE
JOIN MAINTAIN M ON M.SER_DATE = S.S_DATE AND M.SER_CODE = S.WORK_CODE
JOIN EMPLOYEE AS EMP ON M.E_SSN = EMP.SSN
JOIN PERSON AS P ON P.SSN = EMP.SSN
WHERE OW.OWNER_ID = 1001
GROUP BY P.SSN, P.NAME, P.PHONE
ORDER BY SUM(S.HOURS)  DESC;