-- Question#19 - Query 17
USE AMG;

SELECT HG.LOCATION AS 'HANGAR LOCATION',  COUNT(*) AS 'NUMBER OF PLANES'
FROM AIRPLANE A
JOIN HANGAR HG ON HG.NUMBER = A.HG_NO
GROUP BY HG.NUMBER, HG.LOCATION;