-- Question#03 - Query 1
USE AMG;

SELECT A.REG_NO
FROM CORPORATION C
JOIN OWNS O ON C.OWNERID = O.OWNER_ID
JOIN AIRPLANE A ON O.REG_NO = A.REG_NO
WHERE A.REG_NO NOT IN (
	SELECT PS.PREG_NO
	FROM PLANE_SERVICE AS PS
);