-- Question#07 - Query 5
USE AMG;

SELECT A.REG_NO, A.MODEL
FROM CORPORATION C
JOIN OWNS O ON C.OWNERID = O.OWNER_ID
JOIN AIRPLANE A ON O.REG_NO = A.REG_NO
WHERE A.REG_NO IN (
	SELECT PS.PREG_NO
	FROM PLANE_SERVICE AS PS
	WHERE SER_DATE BETWEEN DATEADD(DAY, -7, GETDATE()) AND GETDATE()
);