-- Question#08 - Query 6
USE AMG;

SELECT O.OWNERID, P.NAME AS 'PERSON_NAME', C.NAME AS 'CORPORATION_NAME'
FROM OWNER O
LEFT JOIN PERSON P ON O.OWNERID = P.SSN
LEFT JOIN CORPORATION C ON O.OWNERID = C.OWNERID
JOIN OWNS OW ON O.OWNERID = OW.OWNER_ID
WHERE OW.P_DATE BETWEEN DATEADD(MONTH, -1, GETDATE()) AND GETDATE()