-- Question#09 - Query 7
USE AMG;

SELECT PR.SSN, PR.NAME, count(*) AS 'Auth. to Fly'
FROM PILOT AS PI
JOIN PERSON AS PR ON PI.SSN = PR.SSN
JOIN FLIES AS FL ON FL.SSN = PI.SSN
GROUP BY PR.SSN, PR.NAME;